import type { Locale } from "../../i18n/config";
import type { LegacyArticleId } from "./article-ids";
import type { ArticleBody } from "./article-types";

export type { ArticleId } from "./article-ids";
export type { ArticleBlock, ArticleBody, ListItem } from "./article-types";

export const ARTICLE_CONTENT: Record<LegacyArticleId, Record<Locale, ArticleBody>> = {
  "product-photo-tips": {
    en: {
      blocks: [
        { kind: "paragraph", text: "A product image influences both click-through and conversion. Background removal works best when the source photo already has clean light, clear edges, and enough detail. A few decisions during shooting can save far more time than extra retouching later." },
        { kind: "paragraph", text: "These six practical tips work with either a phone or a camera and make AI cutouts more reliable." },
        { kind: "heading", text: "1. Use a plain background" },
        { kind: "paragraph", text: "A background remover separates foreground from background. A plain white or light-gray surface gives it a much clearer boundary than a patterned table, textured fabric, or cluttered room." },
        { kind: "paragraph", text: "White paper, a matte acrylic sheet, or a small light tent is enough for most products. Make sure the background color contrasts with the product, especially around thin edges." },
        { kind: "heading", text: "2. Use bright, even light" },
        { kind: "paragraph", text: "Low light creates noise and soft edges. Uneven light creates heavy shadows and reflections that can be mistaken for part of the product." },
        { kind: "list", items: [
          { label: "Window light", text: "Shoot beside a window in soft daylight, not direct sun." },
          { label: "Light tent", text: "Useful for frequent product shoots because it keeps light controlled and even." },
          { label: "Two-light setup", text: "Place lights on both sides at roughly 45 degrees to reduce one-sided shadows." },
        ] },
        { kind: "heading", text: "3. Keep the main angle simple" },
        { kind: "paragraph", text: "A straight-on or slightly top-down view usually shows the product clearly and keeps its outline easy to read. Creative side angles can work as secondary images, but the main listing image should normally be direct and easy to compare." },
        { kind: "heading", text: "4. Let the product fill the frame" },
        { kind: "paragraph", text: "Leave some breathing room, but avoid making the subject tiny. A useful starting point is to let the product occupy about 60% to 80% of the frame. This preserves detail and reduces the need for a second crop after cutout." },
        { kind: "heading", text: "5. Prepare transparent and reflective products carefully" },
        { kind: "paragraph", text: "Glass, clear packaging, polished metal, and mirrors have ambiguous edges. Use a contrasting backdrop and control reflections so the silhouette remains visible." },
        { kind: "list", items: [
          { text: "Place a contrasting card behind the product." },
          { text: "Use a polarizing filter when shooting with a compatible camera setup." },
          { text: "Adjust exposure so the outline stays distinct." },
          { text: "Plan for a quick manual edge touch-up after AI processing." },
        ] },
        { kind: "heading", text: "6. Capture enough resolution" },
        { kind: "paragraph", text: "Start with a high-resolution original and resize later for each marketplace. Enlarging a small, blurry file cannot recover missing edge detail. On phones, check that the camera is using its full photo resolution rather than a messaging or screenshot mode." },
        { kind: "heading", text: "Summary" },
        { kind: "paragraph", text: "A plain background, even light, direct angle, useful subject size, careful treatment of difficult materials, and sufficient resolution make up most of a clean cutout workflow." },
        { kind: "paragraph", text: "Once the source photo is ready, process it with edit-photo and inspect the edge at high zoom before publishing." },
      ],
      cta: { title: "Have a product photo ready?", description: "Remove its background locally in your browser and download a transparent PNG.", button: "Remove background free" },
    },
    zh: {
      blocks: [
        { kind: "paragraph", text: "商品主图质量直接影响点击率和转化率。抠图工具很重要，但如果拍摄阶段就把背景、光线和边缘处理好，后期效果会稳定很多，也能减少大量修图时间。" },
        { kind: "paragraph", text: "下面 6 个方法用手机或相机都能做到。" },
        { kind: "heading", text: "1. 选择纯色背景" },
        { kind: "paragraph", text: "抠图工具需要区分商品和背景。纯白或浅灰背景比花纹桌面、布料和杂乱环境更容易识别。白纸、哑光亚克力板或小型摄影棚都可以。" },
        { kind: "paragraph", text: "商品边缘较细或颜色较浅时，背景要与商品形成足够对比。" },
        { kind: "heading", text: "2. 保证充足且均匀的光线" },
        { kind: "paragraph", text: "光线不足会增加噪点并让边缘变糊；光线不均匀会产生重阴影和反光，算法可能把它们误认为商品的一部分。" },
        { kind: "list", items: [
          { label: "自然光", text: "白天靠窗使用柔和散射光，避免直射阳光。" },
          { label: "柔光箱", text: "适合经常拍摄商品，光线更均匀可控。" },
          { label: "双灯布光", text: "左右约 45 度各放一盏灯，减少单侧阴影。" },
        ] },
        { kind: "heading", text: "3. 主图角度保持简单" },
        { kind: "paragraph", text: "正面平视或轻微俯拍通常最容易展示真实比例，轮廓也更清楚。侧面和创意角度可作为细节图，主图优先保证清晰易比较。" },
        { kind: "heading", text: "4. 让商品占据足够画面" },
        { kind: "paragraph", text: "四周保留少量空间，但不要让商品太小。可先以占画面 60% 到 80% 为参考，这样细节更清晰，抠图后也不必再次大幅裁剪。" },
        { kind: "heading", text: "5. 特殊处理透明和反光材质" },
        { kind: "paragraph", text: "玻璃、透明包装、金属和镜面物体的边界容易与背景混在一起，需要控制反光并保持轮廓对比。" },
        { kind: "list", items: [
          { text: "在商品后方放置对比明显的背景板。" },
          { text: "相机拍摄时可根据设备使用偏振镜减少反光。" },
          { text: "调整曝光，让轮廓保持清楚。" },
          { text: "AI 处理后预留一次手动修边。" },
        ] },
        { kind: "heading", text: "6. 拍摄分辨率不要太低" },
        { kind: "paragraph", text: "先保存高分辨率原图，再按不同平台要求缩放。小图放大无法恢复已经丢失的边缘细节。手机拍摄时应确认使用完整照片分辨率，而不是聊天软件压缩图或截图。" },
        { kind: "heading", text: "总结" },
        { kind: "paragraph", text: "纯色背景、均匀光线、清楚角度、合适比例、特殊材质处理和足够分辨率，是干净抠图最重要的六个基础。" },
        { kind: "paragraph", text: "原图准备好后，可以用 edit-photo 处理，并在高倍率下检查边缘再上架。" },
      ],
      cta: { title: "准备好商品图了？", description: "在浏览器本地移除背景，免费下载透明 PNG。", button: "立即免费抠图" },
    },
  },
  "transparent-png-guide": {
    en: {
      blocks: [
        { kind: "paragraph", text: "E-commerce teams often hear the phrase “transparent PNG,” but the difference between a white background and a truly transparent background matters. This guide explains what transparency is, why JPG cannot store it, and how to create a reusable product asset." },
        { kind: "heading", text: "What is a transparent background?" },
        { kind: "paragraph", text: "A white-background photo still contains white pixels. It looks fine on a white page, but becomes a visible rectangle on gray, colored, or gradient layouts. A transparent image removes those background pixels and keeps only the product." },
        { kind: "paragraph", text: "Think of it like a clear sticker: the product can be placed on any design without a white box around it." },
        { kind: "heading", text: "PNG vs JPG" },
        { kind: "list", items: [
          { label: "JPG", text: "Does not support transparency. It is compact and well suited to ordinary photographic images." },
          { label: "PNG", text: "Supports an alpha channel, so background pixels can be transparent. It is usually larger but ideal for cutout assets." },
        ] },
        { kind: "paragraph", text: "If a workflow requires a transparent background, export PNG. A JPG file cannot preserve transparency." },
        { kind: "heading", text: "Why sellers need transparent product assets" },
        { kind: "list", items: [
          { label: "Detail pages", text: "Place the same product on different branded or lifestyle backgrounds." },
          { label: "Campaign banners", text: "Reuse the cutout in promotions without masking it again." },
          { label: "Multi-channel publishing", text: "Adapt one product asset to different marketplace layouts." },
          { label: "Brand libraries", text: "Give designers a clean, reusable source asset." },
        ] },
        { kind: "heading", text: "How to make a transparent PNG" },
        { kind: "heading", level: 3, text: "Method 1: AI background removal" },
        { kind: "paragraph", text: "Upload a product photo, let the model identify the subject, then export the cutout as PNG. This is fast and works well for most clearly photographed products." },
        { kind: "heading", level: 3, text: "Method 2: Manual selection" },
        { kind: "paragraph", text: "For demanding edges, use a desktop editor with pen, selection, and mask tools. It takes longer but gives direct control over individual pixels." },
        { kind: "heading", level: 3, text: "Method 3: Controlled background shooting" },
        { kind: "paragraph", text: "A consistent studio background can simplify batch masking, especially for repeated product shoots. It still needs careful lighting and color separation." },
        { kind: "heading", text: "Checklist before export" },
        { kind: "list", items: [
          { label: "Inspect edges", text: "Zoom in and look for color halos, missing details, and isolated noise." },
          { label: "Keep the original", text: "Retain the source photo so the cutout can be regenerated later." },
          { label: "Use clear names", text: "A suffix such as -transparent helps distinguish cutouts from white-background files." },
          { label: "Standardize dimensions", text: "Keep a product set consistent before batch upload." },
        ] },
        { kind: "heading", text: "Summary" },
        { kind: "paragraph", text: "A transparent PNG is a reusable product layer, not simply a photo with a white background. Use it as the clean source for marketplace images, banners, and branded layouts." },
      ],
      cta: { title: "Need a transparent PNG?", description: "Remove the background locally and export the result at the original dimensions.", button: "Create transparent PNG" },
    },
    zh: {
      blocks: [
        { kind: "paragraph", text: "电商工作中经常会听到“透明背景 PNG”。但白色背景和真正透明的背景不是一回事。下面用简单方式说明透明是什么、为什么 JPG 不能透明，以及如何制作可重复使用的商品素材。" },
        { kind: "heading", text: "什么是透明背景？" },
        { kind: "paragraph", text: "白底照片仍然包含白色像素，在白色页面上看不出来，但放到灰色、彩色或渐变背景上会出现明显白色方块。透明图会移除背景像素，只保留商品。" },
        { kind: "paragraph", text: "可以把它理解为一张透明贴纸，商品能自然放到任何设计背景上。" },
        { kind: "heading", text: "PNG 和 JPG 有什么区别？" },
        { kind: "list", items: [
          { label: "JPG", text: "不支持透明，体积较小，适合普通摄影图片。" },
          { label: "PNG", text: "支持 Alpha 透明通道，背景像素可以没有颜色，适合抠图素材。" },
        ] },
        { kind: "paragraph", text: "只要流程要求透明背景，就应导出 PNG；JPG 无法保留透明信息。" },
        { kind: "heading", text: "为什么卖家需要透明商品素材？" },
        { kind: "list", items: [
          { label: "详情页设计", text: "把同一商品放到不同品牌或场景背景。" },
          { label: "活动横幅", text: "促销设计中复用商品，不必再次抠图。" },
          { label: "多平台发布", text: "一份干净素材适配不同平台版式。" },
          { label: "品牌素材库", text: "给设计人员保留可重复使用的源素材。" },
        ] },
        { kind: "heading", text: "如何制作透明背景 PNG？" },
        { kind: "heading", level: 3, text: "方法一：AI 自动抠图" },
        { kind: "paragraph", text: "上传商品图，让模型识别主体并移除背景，再导出 PNG。速度快，适合大多数拍摄清楚的商品。" },
        { kind: "heading", level: 3, text: "方法二：手动选择与蒙版" },
        { kind: "paragraph", text: "复杂边缘可以用桌面软件的钢笔、选择和蒙版工具精修，耗时更长，但能直接控制细节。" },
        { kind: "heading", level: 3, text: "方法三：统一背景拍摄" },
        { kind: "paragraph", text: "固定摄影背景可简化批量处理，适合重复拍摄同类商品，但仍要注意光线和颜色对比。" },
        { kind: "heading", text: "导出前检查清单" },
        { kind: "list", items: [
          { label: "检查边缘", text: "放大查看色边、缺失细节和孤立杂点。" },
          { label: "保留原图", text: "方便日后重新处理。" },
          { label: "明确命名", text: "可使用 -transparent 后缀区分透明图与白底图。" },
          { label: "统一尺寸", text: "同批商品先统一画布和比例再上传。" },
        ] },
        { kind: "heading", text: "总结" },
        { kind: "paragraph", text: "透明 PNG 是可以重复组合的商品图层，不只是白色背景照片。它适合继续制作主图、横幅和品牌场景图。" },
      ],
      cta: { title: "需要制作透明 PNG？", description: "在浏览器本地移除背景，按原图尺寸导出结果。", button: "制作透明 PNG" },
    },
  },
  "ecommerce-image-specs": {
    en: {
      summary: "Compare current product image requirements for Amazon, Etsy, eBay, Google Merchant Center, and Shopify, with a reusable master-to-export workflow.",
      updatedAt: "2026-09-08T00:00:00.000Z",
      blocks: [
        { kind: "paragraph", text: "The safest way to prepare product images for several marketplaces is not to force one final file everywhere. Keep one sharp master, then export a channel-specific version after checking the current listing form. The comparison below was reviewed against official platform guidance on September 8, 2026." },
        { kind: "paragraph", text: "Quick recommendation: start with a square 2400 × 2400 pixel master, keep a transparent PNG, and create separate white-background and lifestyle exports. This is an edit-photo workflow recommendation, not a universal marketplace requirement." },
        { kind: "heading", text: "Product image requirements at a glance" },
        {
          kind: "table",
          caption: "Marketplace rules and practical export choices — checked September 8, 2026. Category rules can override general guidance.",
          headers: ["Channel", "Current baseline", "Background and overlays", "Practical master-to-export choice"],
          rows: [
            { cells: ["Amazon", "Use at least 1000 px on the longest side for zoom; 1600 px or more is commonly recommended.", "MAIN image: pure white RGB 255/255/255; product fills at least 85%; no text, logos, borders, watermarks, or confusing props.", "Keep a transparent master; export a high-quality white-background listing image."] },
            { cells: ["Etsy", "Etsy recommends listing images at least 2000 px wide and high; the first image should be at least 635 px in both dimensions.", "Transparent PNG is not supported as transparency and may appear black. Use a flattened listing image.", "Export a consistent crop at 2000 px or more; keep transparency only in your private master."] },
            { cells: ["eBay", "At least 500 px on the longest side; eBay recommends 1600 px for the best display.", "No added borders, text, artwork, marketing material, or watermarks.", "Export a clean 1600 px-or-larger image without promotional overlays."] },
            { cells: ["Google Merchant Center", "Use the largest full-size image available. 800 × 800 px is recommended; 500 × 500 becomes the minimum for all products on January 31, 2027.", "No promotional text, price, merchant logo, or calls to action. Google recommends the product occupy 75%–90% of the image.", "Prepare 800–2400 px square files and retain a stable image URL unless the product image changes."] },
            { cells: ["Shopify", "There is no single marketplace crop: the theme controls display. Use a consistent aspect ratio and a high-quality source.", "White, transparent, or lifestyle backgrounds can work when they match the storefront design.", "Keep one large source and test the collection card, product page, zoom, and mobile crop in the active theme."] },
          ],
        },
        { kind: "heading", text: "The reusable workflow we recommend" },
        { kind: "list", items: [
          { label: "1. Preserve the source", text: "Keep the original camera file and never enlarge a small marketplace download as your new master." },
          { label: "2. Remove the background once", text: "Create a transparent PNG that can be reused instead of cutting out the same product for every channel." },
          { label: "3. Inspect difficult edges", text: "Zoom in on reflective surfaces, holes, thin stems, hair, fur, glass, and soft shadows before exporting." },
          { label: "4. Build channel variants", text: "Create a pure-white main image where required, a clean storefront crop, and one or more lifestyle images." },
          { label: "5. Verify inside the seller dashboard", text: "Check the exact category, country, campaign, and current publishing form before upload." },
        ] },
        {
          kind: "imagePair",
          images: [
            { src: "/images/demo/tomato-cutout-demo.webp", alt: "Glossy red tomato timer photographed on a desk before background removal", caption: "Before: desk photo used in the edit-photo demo" },
            { src: "/images/demo/tomato-cutout-result.webp", alt: "Red tomato timer isolated from the desk and shown on a transparency checkerboard", caption: "After: browser-local cutout preview" },
          ],
          caption: "A real site demo asset. The broad silhouette and green stem are retained, but a seller should still inspect the bottom shadow and fine edge before creating a marketplace-specific final image.",
        },
        { kind: "internalLink", text: "Need the complete cutout process before resizing?", label: "Follow the product-photo background removal workflow", href: "/blog/remove-background-product-photos" },
        { kind: "heading", text: "Amazon" },
        { kind: "paragraph", text: "Amazon MAIN images have the strictest background rule in this comparison: show the actual product on pure white RGB 255/255/255, let the product fill at least 85% of the frame, and avoid text, logos, borders, watermarks, and props that could confuse the buyer. A transparent PNG is useful as a working master, but the final MAIN image needs a white background." },
        { kind: "source", text: "Official help reference and current Amazon staff guidance:", label: "Amazon product image requirements", href: "https://sellercentral.amazon.com/help/hub/reference/external/G1881" },
        { kind: "heading", text: "Etsy" },
        { kind: "paragraph", text: "Etsy recommends listing photos at least 2000 pixels wide and high. Do not upload a transparent PNG expecting the listing to stay transparent: Etsy states that transparent areas can appear black. Flatten the product onto the intended background before listing, while keeping a separate transparent master for future designs." },
        { kind: "source", text: "Official requirement checked September 2026:", label: "Etsy image requirements and best practices", href: "https://help.etsy.com/hc/en-gb/articles/115015663347-Requirements-and-Best-Practices-for-Images-in-Your-Etsy-Shop" },
        { kind: "heading", text: "eBay" },
        { kind: "paragraph", text: "eBay requires at least one photo with 500 pixels on the longest side and recommends 1600 pixels for a stronger display. Current policy prohibits added borders, text, artwork, marketing material, and watermarks. Use secondary photos to show condition and angles rather than packing several views into the main image." },
        { kind: "source", text: "Official policy checked September 2026:", label: "eBay picture policy", href: "https://www.ebay.com/help/policies/listing-policies/picture-policy?id=4370" },
        { kind: "heading", text: "Google Merchant Center" },
        { kind: "paragraph", text: "Google recommends the largest full-size image available, at least 800 × 800 pixels as a practical target, with the product occupying roughly 75%–90% of the frame. It also announced a 500 × 500 minimum for all product images beginning January 31, 2027. Promotional copy, prices, calls to action, and merchant logos do not belong in the main product image." },
        { kind: "source", text: "Official transition guidance checked September 2026:", label: "Google Merchant Center image-size requirements", href: "https://support.google.com/merchants/answer/12159030?hl=en" },
        { kind: "heading", text: "Shopify" },
        { kind: "paragraph", text: "Shopify is a storefront system rather than a marketplace with one universal main-image crop. The active theme determines how media is cropped in collection cards and product pages. Keep the source high quality, use the same aspect ratio across a product set, add useful alt text, and test desktop plus mobile before publishing." },
        { kind: "source", text: "Official product-media guidance checked September 2026:", label: "Shopify product media", href: "https://help.shopify.com/en/manual/products/product-media" },
        { kind: "heading", text: "Pre-publish quality check" },
        { kind: "list", items: [
          { text: "Open the current publishing form for the exact country and category." },
          { text: "Confirm dimensions, aspect ratio, file size, format, image count, and overlay restrictions." },
          { text: "Check every edge at 200% zoom and look for halos, missing holes, leftover background, and clipped shadows." },
          { text: "Verify that the product is not cropped and occupies the required share of the frame." },
          { text: "Save the original, transparent master, and final channel export as separate files with clear names." },
        ] },
        {
          kind: "faq",
          title: "Product image specification FAQ",
          items: [
            { question: "Can I upload the same image to every marketplace?", answer: "Use the same high-resolution source, but export separate final files. Background rules, crop behavior, overlays, and minimum dimensions differ by channel and category." },
            { question: "What is the best size for a reusable master image?", answer: "There is no universal required size. A sharp square file around 2400 × 2400 pixels is a practical working master for many products because it can be reduced for common marketplace needs without enlargement." },
            { question: "Should the master file be PNG or JPEG?", answer: "Keep a transparent PNG after background removal and preserve the original camera file. Export JPEG or a flattened PNG when a marketplace requires a solid background or does not preserve transparency." },
            { question: "Does every marketplace require a pure white background?", answer: "No. Amazon MAIN images generally require pure white, while Shopify storefronts can use white, transparent, or lifestyle backgrounds. Always check the exact channel and category." },
            { question: "Why should I keep a transparent version if the final image is white?", answer: "The transparent file lets you create future white, branded, seasonal, and lifestyle variants without cutting out the product again." },
          ],
        },
      ],
      cta: { title: "Preparing images for several marketplaces?", description: "Create a clean transparent master first, then export each channel variant.", button: "Start with a free cutout" },
    },
    zh: {
      summary: "对照 Amazon、Etsy、eBay、Google Merchant Center 和 Shopify 当前商品图要求，并按可复用母版流程导出渠道成品图。",
      updatedAt: "2026-09-08T00:00:00.000Z",
      blocks: [
        { kind: "paragraph", text: "同时给多个平台准备商品图，最稳妥的方法不是拿一个最终文件到处上传，而是保留一份清晰母版，再根据当前发布表单导出渠道版本。下面的对照内容已于 2026 年 9 月 8 日根据平台官方资料核对。" },
        { kind: "paragraph", text: "直接建议：先保存一份 2400 × 2400 像素左右的方形工作母版、一个透明 PNG，再分别导出白底图和场景图。这是 edit-photo 的实用工作流建议，不是所有平台统一规定。" },
        { kind: "heading", text: "五个平台商品图要求快速对照" },
        {
          kind: "table",
          caption: "平台规则与导出建议——核对日期：2026 年 9 月 8 日。具体类目规则可能覆盖通用要求。",
          headers: ["平台", "当前基础要求", "背景和叠加元素", "推荐导出方式"],
          rows: [
            { cells: ["Amazon", "长边至少 1000 px 才能使用缩放，通常建议 1600 px 以上。", "MAIN 主图纯白 RGB 255/255/255；商品至少占 85%；不要文字、Logo、边框、水印或容易误解的道具。", "保留透明母版，另导出高质量白底主图。"] },
            { cells: ["Etsy", "建议商品图宽和高至少 2000 px；第一张图宽和高至少 635 px。", "不支持透明 PNG 的透明效果，透明区域可能显示为黑色。", "导出 2000 px 以上的统一裁切成品图；透明母版仅内部保存。"] },
            { cells: ["eBay", "长边至少 500 px，官方建议 1600 px 以获得更好展示。", "不允许额外边框、文字、图形、营销信息或水印。", "导出 1600 px 以上、无促销叠加的干净图片。"] },
            { cells: ["Google Merchant Center", "建议至少 800 × 800 px；2027 年 1 月 31 日起所有商品图最低 500 × 500 px。", "不要促销文字、价格、商家 Logo 或行动号召；建议商品占画面 75%–90%。", "准备 800–2400 px 方图，商品图片未变化时保持图片 URL 稳定。"] },
            { cells: ["Shopify", "没有统一的平台裁切比例，实际展示取决于店铺主题；同一商品组保持一致比例。", "可使用白底、透明或场景背景，取决于店铺设计。", "保留高清源文件，并检查当前主题的列表卡片、详情页、缩放和移动端裁切。"] },
          ],
        },
        { kind: "heading", text: "我们推荐的可复用工作流" },
        { kind: "list", items: [
          { label: "1. 保留原始文件", text: "保存相机原图，不要把低清平台下载图放大后当作新母版。" },
          { label: "2. 只抠一次", text: "先生成可以重复使用的透明 PNG，避免每个平台重新抠一遍。" },
          { label: "3. 检查复杂边缘", text: "放大检查反光面、孔洞、细杆、毛发、玻璃和柔和阴影。" },
          { label: "4. 制作渠道版本", text: "按需要生成纯白主图、店铺统一裁切图和场景图。" },
          { label: "5. 在卖家后台复核", text: "上传前检查目标国家、类目、活动和当前发布表单。" },
        ] },
        {
          kind: "imagePair",
          images: [
            { src: "/images/demo/tomato-cutout-demo.webp", alt: "抠图前放在桌面上拍摄的红色番茄计时器", caption: "处理前：网站演示使用的桌面实拍图" },
            { src: "/images/demo/tomato-cutout-result.webp", alt: "从桌面背景分离并显示在透明棋盘格上的红色番茄计时器", caption: "处理后：浏览器本地抠图预览" },
          ],
          caption: "这是网站实际演示素材。主体轮廓和绿色叶片得到保留，但正式上架前仍应检查底部阴影和细小边缘，再生成对应平台的最终图。",
        },
        { kind: "internalLink", text: "想先了解怎样拍出更容易处理的原图？", label: "查看商品图拍摄的 6 个要点", href: "/blog/product-photo-tips" },
        { kind: "heading", text: "亚马逊（Amazon）" },
        { kind: "paragraph", text: "Amazon MAIN 主图在这几个平台中对白底要求最严格：展示实际销售商品，背景为纯白 RGB 255/255/255，商品至少占画面 85%，不要添加文字、Logo、边框、水印或容易让买家误解的道具。透明 PNG 适合做工作母版，但 MAIN 最终图需要白色背景。" },
        { kind: "source", text: "Amazon 官方帮助参考：", label: "Amazon 商品图片要求", href: "https://sellercentral.amazon.com/help/hub/reference/external/G1881" },
        { kind: "heading", text: "Etsy" },
        { kind: "paragraph", text: "Etsy 建议商品图的宽和高至少为 2000 像素。不要直接上传透明 PNG 并期待继续透明：Etsy 说明透明区域可能显示为黑色。上架前应把商品合成到最终背景，同时另存一份透明母版供后续设计。" },
        { kind: "source", text: "2026 年 9 月核对官方要求：", label: "Etsy 图片要求与最佳实践", href: "https://help.etsy.com/hc/en-gb/articles/115015663347-Requirements-and-Best-Practices-for-Images-in-Your-Etsy-Shop" },
        { kind: "heading", text: "eBay" },
        { kind: "paragraph", text: "eBay 要求至少一张照片，长边最低 500 像素，并建议使用 1600 像素以获得更好的展示。当前政策不允许额外边框、文字、图形、营销信息和水印。商品状态和不同角度应使用附图展示，而不是全部挤到主图里。" },
        { kind: "source", text: "2026 年 9 月核对官方政策：", label: "eBay 图片政策", href: "https://www.ebay.com/help/policies/listing-policies/picture-policy?id=4370" },
        { kind: "heading", text: "Google Merchant Center" },
        { kind: "paragraph", text: "Google 建议提交可用的最大完整图片，实际准备时可把 800 × 800 像素作为起点，商品约占画面 75%–90%。Google 已宣布从 2027 年 1 月 31 日起，所有商品图最低为 500 × 500 像素。主图不应出现促销文案、价格、行动号召或商家 Logo。" },
        { kind: "source", text: "2026 年 9 月核对官方过渡说明：", label: "Google Merchant Center 图片尺寸要求", href: "https://support.google.com/merchants/answer/12159030?hl=zh-Hans" },
        { kind: "heading", text: "Shopify" },
        { kind: "paragraph", text: "Shopify 是店铺系统，不是只有一种统一主图比例的平台。商品媒体怎样裁切取决于当前主题。源文件应保持高质量，同一商品组使用一致比例，填写有意义的替代文字，并在发布前检查电脑端和移动端展示。" },
        { kind: "source", text: "2026 年 9 月核对官方商品媒体说明：", label: "Shopify 商品媒体", href: "https://help.shopify.com/zh-CN/manual/products/product-media" },
        { kind: "heading", text: "发布前质量检查" },
        { kind: "list", items: [
          { text: "打开目标国家和类目的当前发布表单。" },
          { text: "核对尺寸、比例、文件大小、格式、数量和叠加元素限制。" },
          { text: "在 200% 倍率检查色边、漏抠孔洞、背景残留和被截断的阴影。" },
          { text: "确认商品没有被裁断，并达到平台要求的画面占比。" },
          { text: "分别保存原图、透明母版和渠道最终图，并采用清楚的文件名。" },
        ] },
        {
          kind: "faq",
          title: "商品图片规格常见问题",
          items: [
            { question: "同一张图片可以上传到所有平台吗？", answer: "可以共用同一份高清源文件，但最终图应分别导出。不同渠道和类目的背景、裁切、叠加元素及最低尺寸要求并不相同。" },
            { question: "通用工作母版做多大比较合适？", answer: "没有所有平台统一要求的尺寸。对多数商品来说，清晰的 2400 × 2400 像素方图是实用起点，可以向下缩小满足常见需求，避免放大低清图。" },
            { question: "母版应该保存 PNG 还是 JPEG？", answer: "抠图后保存透明 PNG，同时保留相机原图。平台要求实色背景或不保留透明时，再导出 JPEG 或合成背景后的 PNG。" },
            { question: "所有平台都要求纯白背景吗？", answer: "不是。Amazon MAIN 主图通常要求纯白，而 Shopify 店铺可以使用白底、透明背景或场景图。应以具体平台和类目要求为准。" },
            { question: "最终图是白底，为什么还要保存透明版本？", answer: "透明文件可以继续制作白底、品牌色、节日和生活场景版本，不需要以后重复抠图。" },
          ],
        },
      ],
      cta: { title: "需要适配多个平台？", description: "先制作干净的透明商品母版，再导出不同渠道版本。", button: "从免费抠图开始" },
    },
  },
};
